class HashTagGroup {
  final String title;
  final List<String> tags;

  const HashTagGroup(this.title, this.tags);
}

const HashTagGroup adv = HashTagGroup("Adv", [
  'hkinfluencer ',
  'hkbloggers ',
  'hkblogger ',
  'bloggerhk ',
  'hkkol ',
  'kolhk ',
  'asianblogger ',
  'hklifestyleblogger ',
  'hkfashionblogger ',
  'hktravelblogger ',
  'hkbeautyblogger ',
  'influencerstyle ',
  'hkfoodblogger ',
  'hkfoodieblogger ',
  'hkmicroinfluencer ',
  'hkshare ',
  'hkbeauty ',
  'presslogicgirls ',
  'hkpr ',
  'hkmarketing ',
  'hkevent ',
  'hkevents ',
  '網紅 '
]);
const HashTagGroup con = HashTagGroup("Con", [
  '美瞳 ',
  '美妝 ',
  '美妝分享 ',
  '眼妝 ',
  'hkbeauty ',
  'hkinfluencer ',
  'hkblogger ',
  '好物分享 ',
  'hkbeautyblogger ',
  'hkkol ',
  'presslogicgirls ',
  'hkmicroinfluencer ',
  'hkmakeup ',
  'hkinstagram ',
  '852girl ',
  '素敵女子 ',
  'hkbeauty ',
  'hkshare ',
  'hkgirlstyle ',
  'sheisfromhk ',
  'hkmodel'
]);
const HashTagGroup generic = HashTagGroup("Generic", [
  'hkgirl ',
  'hkiggirl ',
  'hkiger ',
  'hkger ',
  'hongkonggirl ',
  'hkinstagram ',
  '852girl ',
  'hkgal ',
  '女孩 ',
  '香港女孩',
  'capturehongkong ',
  'explorehongkong ',
  '香港🇭🇰 ',
  'hongkonginsta ',
  'thisishongkong',
  'hk_portrait ',
  'hkportrait ',
  '人像 ',
  '写真好きな人と繋がりたい',
  'hktraveller ',
  'hkinfluencer ',
  'hkkol ',
  'hklifestyleblogger ',
  'hkfashionblogger ',
  'hktravelblogger ',
  'hkblogger ',
  'asianblogger',
  'qurantinelife ',
  '香港打卡'
]);
const HashTagGroup hair = HashTagGroup("Hair", ['hkhair ', 'hairstyles ', '髮型 ', '日系髮型 ', 'サロモ ', 'サロンモデル']);
const HashTagGroup fashion = HashTagGroup("Fashion", [
  'hklifestyleblogger ',
  'hkblogger ',
  'hkfashionblogger ',
  'hkbeautyblogger ',
  'ootd ',
  'wiwt ',
  'hkootd ',
  'instafashion ',
  'ootdhk ',
  'ootdinspiration ',
  '秋冬穿搭 ',
  '文青 ',
  '文青穿搭 ',
  '襯衫 ',
  '日常穿搭 ',
  '穿搭分享 ',
  'motd'
]);
const HashTagGroup travel = HashTagGroup("Travel", [
  '香港好去處 ',
  '假日好去處',
  'capturehongkong ',
  'explorehongkong ',
  'homekong ',
  'hkdaily ',
  'hktraveller ',
  'wantogo ',
  'hongkonginsta ',
  'thisishongkong ',
  'utravelhk ',
  'beautifuldestination ',
  'travelaroundtheworld ',
  '旅行好き',
  '旅行写真 ',
  '旅の思い出 ',
  '旅の記録 ',
  '旅女 ',
  'girlswhotravel ',
  'travelyam ',
  '香港打卡 ',
  'flydayhk ',
  '香港街拍 ',
  '街拍 ',
  '旅行好き女子 ',
  'trippacker ',
  'eztravel ',
  '美景'
]);

const List<HashTagGroup> hashTagList = [adv, con, generic, hair, fashion, travel];